{
 "title": "Syncthing Metrics",
 "description": "Syncthing Metrics from the native Prometheus metrics endpoint",
 "tags": [
  "syncthing",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(syncthing_events_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Scanned Items",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(syncthing_scanner_scanned_items_total{instance=~\"$instance\"}) by (folder)",
     "legendFormat": "{{folder}}"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(syncthing_events_total{instance=~\"$instance\"}) by (event)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Folder State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(syncthing_model_folder_state{instance=~\"$instance\"}) by (folder)",
     "legendFormat": "{{folder}}"
    }
   ]
  },
  {
   "title": "Total Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(syncthing_model_folder_processed_bytes_total{instance=~\"$instance\"}) by (folder)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes Recieved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(syncthing_protocol_recv_bytes_total{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(syncthing_protocol_sent_bytes_total{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Events - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "sum(syncthing_events_total{instance=~\"$instance\"}) by (event)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}