# One CLI to format the code tree - https://git.numtide.com/numtide/treefmt

[global]
excludes = [
    ".gitignore",
    ".gitattributes",
    "*/.gitattributes",
    "*.gpg",
    "LICENSE",
    "*.dat",
    "*.lock",
    "*.txt",
    "*.conf",
    "*.age",
]

[formatter.nixfmt-rfc-style]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.prettier]
command = "prettier"
excludes = []
includes = ["*.cjs", "*.css", "*.html", "*.js", "*.json", "*.json5", "*.jsx", "*.md", "*.mdx", "*.mjs", "*.scss", "*.ts", "*.tsx", "*.vue", "*.yaml", "*.yml"]
options = ["--write"]

[formatter.ruff-format]
command = "ruff"
excludes = []
includes = ["*.py", "*.pyi"]
options = ["format"]
